### ISSUE TITLE
Missing app updates

### ISSUE THREAD

**Issue by Simounet** [nextcloud/notifications#207]
### Steps to reproduce
1. Wait for an app update

### Expected behaviour
Should see a notification about the app update.

### Actual behaviour
Nothing shows up even if I have few rows on the `oc_notifications` table:
app: updatenotification
subject: update_available

Thanks for this amazing piece of software anyway!

**Comment by nickvergessen** [comment]
Works fine here. Can you post the full database entry?

**Comment by Simounet** [comment]
```
notification_id: 48
               app: updatenotification
              user: Simounet
         timestamp: 1542909615
       object_type: core
         object_id: 14.0.4.2
           subject: update_available
subject_parameters: {"version":"Nextcloud 14.0.4"}
           message:
message_parameters: []
              link:
           actions: []
              icon:
```
